### ISSUE TITLE
centos 5.11 编译不过

### ISSUE THREAD

**Issue by gollon** [bitleak/twemproxy#18]
src/event/nc_epoll.c:337: undefined reference to `epoll_pwait'
collect2: ld returned 1 exit status
make[3]: *** [nutcracker] Error 1
make[3]: Leaving directory `/home/src/twemproxy-1.0.4/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/src/twemproxy-1.0.4/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/src/twemproxy-1.0.4'
make: *** [all] Error 2

**Comment by git-hulk** [comment]
@gollon epoll_pwait 是 kernel 2.6.19 之后加入的，centos 5.11 内核版本过低，包括 reuse port 也不能使用，那么实际上能用到的只有配置 reload 的功能，建议使用更新的发行版，比如 6.5 以上
