### ISSUE TITLE
twemproxy work core

### ISSUE THREAD

**Issue by watchpoints** [bitleak/twemproxy#21]
如果 work直接拉起，里面正在处理信息不是没有了吗？
这样不做到100%

**Comment by git-hulk** [comment]
@aleafboat 你这边的问题不太确定是问下面的场景:

1. worker core(异常退出) 那么正在处理的请求一定是丢掉的， core 本身是很严重 bug, 非预期可处理场景我们一般不考虑
2. worker reload 的时候，master 负责拉起新的 worker， 然后老 worker 退出。老 worker 会等到 `worker_shutdown_timeout `（配置文件里的配置，默认 30s）之后退出，中间如果老 worker 的长连接有请求，在处理之后会顺便关闭长连接，大部分语言 SDK 可以自动重连(如 phpredis)。如果是之后发送请求，那么则会受到 rst 包
