### ISSUE TITLE
Error in some command

### ISSUE THREAD

**Issue by XiaoKa741** [bitleak/twemproxy#22]
i use HMSET, sometimes it is failed.

ERR Forbidden Command: multi_hset
 ERR Forbidden Command: multi_hset
 ERR Forbidden Command: multi_hset
 ERR Forbidden Command: multi_hset
 ERR Forbidden Command: multi_hset

**Comment by git-hulk** [comment]
@XiaoKa741 The error message was generated by your SDK, not Twemproxy. Can you provide more information, like the Redis/Twemproxy version, what's your client language?

**Comment by XiaoKa741** [comment]
>go client(go-redis)，
> i use HMSET, sometimes it is failed.
> 
> ERR Forbidden Command: multi_hset
> ERR Forbidden Command: multi_hset
> ERR Forbidden Command: multi_hset
> ERR Forbidden Command: multi_hset
> ERR Forbidden Command: multi_hset

**Comment by XiaoKa741** [comment]
sorry,it's my fault.i set db readonly by accident @git-hulk

**Comment by git-hulk** [comment]
@XiaoKa741 OK, I would close the issue later.
