### ISSUE TITLE
[question] apline lib-musl support

### ISSUE THREAD

**Issue by axot** [bitleak/twemproxy#23]
Thanks for creating this version of twemproxy with many improvements and bug fixes, one benefit of this one is multi-process support, so I have a question about is it working in alpine, we are want to run this in container, alpine will make more slim image.

**Comment by git-hulk** [comment]
hey @axot 

I'm sorry that we never run it in the container, but twemproxy's binary only depend on the Glibc, so I think it should be easy to fit it in alpine.

**Comment by axot** [comment]
Sure, because alpine did not use glibc, so I guess it may better run in debian?

**Comment by git-hulk** [comment]
AHA, Debian is ok, but our production os is Centos
